Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,24 +1,69 @@
-name: Passing Values Between Jobs
+name: Build and Deploy
 
-on: [push]
+on:
+  pull_request:
+    branches:
+      - main
 
 jobs:
-  job1:
+
+  build:
     runs-on: ubuntu-latest
+    permissions: write-all
     outputs:
-      my_output: ${{ steps.step1.outputs.my_output }}
-
+      version: ${{ steps.read_variables.outputs.stableVersion }}
     steps:
-      - name: Step 1
-        id: step1
-        run: |
-          echo "::set-output name=my_output::Hello, World!"
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-  job2:
-    needs: job1
+      - name: Read variables
+        id: read_variables
+        run: |
+          stableVersion=$(grep "stableVersion:" .github/variables.yml | awk -F ": " '{print $2}')
+          echo "::set-output name=stableVersion::$stableVersion"
+          
+          
+      - name: Get Tags
+        id: get_tags
+        run: |
+          tags=$(git ls-remote --tags origin | awk '{print $2}' | awk -F/ '{print $NF}')
+          echo "::set-output name=tags::$tags"
+          
+      - name: Run build
+        run: |
+          echo "Running build task..."
+          existingtags="${{ steps.get_tags.outputs.tags }}"
+          current_tag="${{ steps.read_variables.outputs.stableVersion }}"
+          if [[ $existingtags =~ (^|[[:space:]])$current_tag($|[[:space:]]) ]]; then
+            echo "Tag $current_tag exists! Failing the build."
+            exit 1
+          else
+            echo "Tag $current_tag does not exist. Build can continue."
+          fi
+
+  deploy:
+    needs: build
     runs-on: ubuntu-latest
-
+    permissions: write-all
+    if: |
+      ${{ github.head_ref }} == "main" && ${{ github.base_ref }} == "main" && github.event.pull_request.merged == true
+      
     steps:
-      - name: Step 2
-        run: |
-          echo "Received input value: ${{ needs.job1.outputs.my_output }}"
+      - name: Create Release
+        id: create_release
+        uses: actions/create-release@latest
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ needs.build.outputs.version }}
+          release_name: Release${{ needs.build.outputs.version }}
+          body: |
+            Changes in this Release
+            - First Change
+            - Second Change
+            - Third Change
+          draft: false
+          prerelease: false
+          
+          
+          
