Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,36 +1,69 @@
-# This is a basic workflow to help you get started with Actions
+name: Build and Deploy
 
-name: CI
-
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
-  push:
-    branches: [ "main" ]
   pull_request:
-    branches: [ "main" ]
+    branches:
+      - main
 
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
+
   build:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
+    permissions: write-all
+    
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Read variables
+        id: read_variables
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          stableVersion=$(grep "stableVersion:" .github/variables.yml | awk -F ": " '{print $2}')
+          echo "::set-output name=stableVersion::$stableVersion"
+          
+          
+      - name: Get Tags
+        id: get_tags
+        run: |
+          tags=$(git ls-remote --tags origin | awk '{print $2}' | awk -F/ '{print $NF}')
+          echo "::set-output name=tags::$tags"
+          
+      - name: Run build
+        run: |
+          echo "Running build task..."
+          existingtags="${{ steps.get_tags.outputs.tags }}"
+          current_tag="${{ steps.read_variables.outputs.stableVersion }}"
+          if [[ $existingtags =~ (^|[[:space:]])$current_tag($|[[:space:]]) ]]; then
+            echo "Tag $current_tag exists! Failing the build."
+            exit 1
+          else
+            echo "Tag $current_tag does not exist. Build can continue."
+          fi
+
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    permissions: write-all
+    if: |
+      ${{ github.head_ref }} == "main" && ${{ github.base_ref }} == "main" && github.event.pull_request.merged == true
+      
+    steps:
+    
+      - name: Create Release
+        id: create_release
+        uses: actions/create-release@latest
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ needs.build.outputs.stableVersion }}
+          release_name: Release${{ needs.build.outputs.stableVersion }}
+          body: |
+            Changes in this Release
+            - First Change
+            - Second Change
+            - Third Change
+          draft: false
+          prerelease: false
+          
+          
+          
