Update TriggerTagandRelease.yml

diff --git a/.github/workflows/TriggerTagandRelease.yml b/.github/workflows/TriggerTagandRelease.yml
--- a/.github/workflows/TriggerTagandRelease.yml
+++ b/.github/workflows/TriggerTagandRelease.yml
@@ -43,14 +43,10 @@ jobs:
             echo "The current tag already exists in the main branch."
      
             conclusion=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \"https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}" \| jq -r '.conclusion')
-
-            if [[ "$conclusion" == "failure" ]]; then
-              echo "::error::Build failed. Blocking PR merge."
-              gh pr merge ${{ github.event.pull_request.number }} --merge --auto
-              exit 1
-            fi
-          
-            
+            echo "::error::Build failed. Blocking PR merge."
+            gh pr merge ${{ github.event.pull_request.number }} --merge --auto
+            exit 1
+           
           else
             echo "The current tag is unique and doesn't exist in the main branch."
           fi
